[options]

; Database connection
db_host = localhost
db_port = 5432
db_user = odoouser
db_password = odoouser
db_name = hoteldata2

; Server port
http_port = 8071

; Admin password
admin_passwd = admin

; Disable demo data
without_demo = True

; Logging
;logfile = /var/log/odoo/odoo19.log

; Addon paths (relative)
addons_path = addons,odoo/addons,mukwebthemeaddon,myaddons
;wkhtmltopdf for PDF reports
wkhtmltopdf = /usr/local/bin/wkhtmltopdf

// app password:dztz ysdl looy kubp